### ISSUE TITLE
使用中间人流量分析，没有日志，手机app也卡住

### ISSUE THREAD

**Issue by r00tit** [rev1si0n/lamda#10]
前置条件：lamda已经开启
按照tools的文档，使用命令python3 -u startmitm.py 192.168.1.2:com.some.package开启中间人分析流量，但是打开app，卡住。命令开启的web页面也没有流量日志
![image](https://user-images.githubusercontent.com/9130966/198293137-f4442cd8-9c80-44d7-aabd-e0dec8877e20.png)

**Comment by rev1si0n** [comment]
也就是说前两个问题已经解决了，python3 -u startmitm.py 192.168.1.2:com.some.package 不知道你是否连 com.some.package 也复制了进去。

**Comment by rev1si0n** [comment]
如果复制了进去的话，那你的命令肯定是执行失败的，app 卡住，请确保你的这台 debian 没有开启防火墙。

**Comment by r00tit** [comment]
> 如果复制了进去的话，那你的命令肯定是执行失败的，app 卡住，请确保你的这台 debian 没有开启防火墙。

没有复制进去，我是为了打码才用你的命令。我试下关闭防火墙。另外前两个问题没解决，我是换了linux系统才用的了，原来用windows

**Comment by r00tit** [comment]
> 如果复制了进去的话，那你的命令肯定是执行失败的，app 卡住，请确保你的这台 debian 没有开启防火墙。其次，确保安装时提出的条件都符合，重启手机重试。

安装完还需要做什么操作吗，我是启动了lamda就运行这条命令，不知道还有没有其他要运行的

**Comment by rev1si0n** [comment]
无需其他操作，请不要指定APP使用全局中间人使用系统浏览器看看是否有问题，顺便提供 startmitm.py 的运行日志

**Comment by r00tit** [comment]
> 无需其他操作，请不要指定APP使用全局中间人在安卓内用系统浏览器访问百度看看是否有问题，顺便提供 startmitm.py 的运行日志

这是startmitm.py日志![Uploading image.png…]()，
用浏览器打开百度现象是一样的，也会卡住，没有流量

**Comment by r00tit** [comment]
> 无需其他操作，请不要指定APP使用全局中间人在安卓内用系统浏览器访问百度看看是否有问题，顺便提供 startmitm.py 的运行日志

这是startmitm.py日志
用浏览器打开百度现象是一样的，也会卡住，没有流量，pc的linux防火墙是关闭的
![image](https://user-images.githubusercontent.com/9130966/198472393-edcbed0a-6829-4b8b-a6f8-653756ea384c.png)

**Comment by rev1si0n** [comment]
知道问题了，已经修复了但是还没有放上来，你可以先这样做
在执行 startmitm.py 之前，获取本机那个 172.20.10.x 网段的地址（ifconfig）
然后先执行命令
```bash
export LANIP=172.20.10.x
```
再 startmitm 即可。

**Comment by r00tit** [comment]
> 知道问题了，已经修复了但是还没有放上来，你可以先这样做 在执行 startmitm.py 之前，获取本机那个 172.20.10.x 网段的地址（ifconfig） 然后先执行命令
> 
> ```shell
> export LANIP=172.20.10.x
> ```
> 
> 再 startmitm 即可。

linux解决了，如果我要在windows用报这个错咋办
![image](https://user-images.githubusercontent.com/9130966/198497075-5a1f1536-fe62-4efe-ad02-04f248da9adc.png)

**Comment by rev1si0n** [comment]
我这边无法复现，请尝试在一个全新的 virtualenv 中安装或者尝试安装高版本的 Python

**Comment by r00tit** [comment]
> 知道问题了，已经修复了但是还没有放上来，你可以先这样做 在执行 startmitm.py 之前，获取本机那个 172.20.10.x 网段的地址（ifconfig） 然后先执行命令
> 
> ```shell
> export LANIP=172.20.10.x
> ```
> 
> 再 startmitm 即可。

![image](https://user-images.githubusercontent.com/9130966/198512109-e217051d-5446-4dfb-90c2-a2388f3da0a1.png)
linux没有问题了
windows没法加这个命令，报错了
