### ISSUE TITLE
支持xpath的selector

### ISSUE THREAD

**Issue by ykk648** [rev1si0n/lamda#14]
text/description 没有，resourceID重复的情况下如何选择element？

**Comment by rev1si0n** [comment]
方便的话提供个类似APP，text这些无法找到，有可能只是被顶层元素覆盖但实际上仍然可以选择。

**Comment by ykk648** [comment]
谢谢 尽量使用text/description代替

**Comment by ykk648** [comment]
element 无法多选，仍然是上面的情况，假如两个button text完全一致，resourceID/description 为空，无法选择第二个button

**Comment by ykk648** [comment]
解决了  通过instance=0/1控制

**Comment by ykk648** [comment]
uiautomator2的 child sibling xpath, 还是刚需，例如右边一列签到可点击，左边是描述不可点击，需要通过定位描述的sibling来确定点击哪一个签到，假如前后顺序会变，除非像airtest加图像识别，用instance也无法定位

**Comment by ykk648** [comment]
尝试 

`
protos.Selector(** {'text':' ', 'childOrSibling':['sibling'], 'childOrSiblingSelector': [protos.Selector(**{'text':''})]})
`
没有成功

**Comment by rev1si0n** [comment]
昨天晚上修复了，加入了child sibling支持，xpath暂时不会加入，周末会发个版本

**Comment by rev1si0n** [comment]
已发

**Comment by ykk648** [comment]
thx
