### ISSUE TITLE
mitmproxy模块启动失败

### ISSUE THREAD

**Issue by yinengp** [rev1si0n/lamda#15]
电脑是window10，启动mitmproxy时报以下错误，请问这是什么原因呢
![impicture_20221206_200548](https://user-images.githubusercontent.com/30826471/205908341-b16db1e9-09da-4a66-b0eb-8c5a4d329977.png)

**Comment by rev1si0n** [comment]
尝试 pip install -U --force-reinstall lamda 看看能否解决

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yinengp ***@***.***>
发送时间: Tuesday, December 6, 2022 8:07:48 PM
收件人: rev1si0n/lamda ***@***.***>
抄送: Subscribed ***@***.***>
主题: [rev1si0n/lamda] mitmproxy模块启动失败 (Issue #15)


电脑是window10，启动mitmproxy时报以下错误，请问这是什么原因呢
[impicture_20221206_200548]<https://user-images.githubusercontent.com/30826471/205908341-b16db1e9-09da-4a66-b0eb-8c5a4d329977.png>

―

**Comment by rev1si0n** [comment]
python版本是什么，或者你尝试用 release 里的 startmitm-standalone.zip 看看

**Comment by yinengp** [comment]
python版本为：3.9.7
startmitm-standalone.zip也使用过了，报一样的错。
我在mac电脑上使用时表现正常的

**Comment by rev1si0n** [comment]
你先试一下新建 virtualenv，在新的环境里看看有没有问题，顺便贴一下 pip freeze 命令的结果(去掉你不想出现的东西)

**Comment by rev1si0n** [comment]
还有确保你系统上没有开代理

**Comment by yinengp** [comment]
好的，我试一下

**Comment by yinengp** [comment]
1.在新建的virtualenv上执行的，一样的报错
2.系统没有开代理
3. 这是 pip freeze 的结果：

(env_1) D:\Temp\Tools\lamda-master\tools>pip freeze
asgiref==3.5.2
asn1crypto==1.5.1
Brotli==1.0.9
certifi==2022.9.24
cffi==1.15.1
click==8.1.3
colorama==0.4.6
cryptography==38.0.4
Flask==2.2.2
grpc-interceptor==0.14.1
grpcio==1.47.2
grpcio-tools==1.47.2
h11==0.14.0
h2==4.1.0
hpack==4.0.0
hyperframe==6.0.1
importlib-metadata==5.1.0
itsdangerous==2.1.2
Jinja2==3.1.2
kaitaistruct==0.10
lamda==3.0.50
ldap3==2.9.1
MarkupSafe==2.1.1
mitmproxy==9.0.1
mitmproxy_wireguard==0.1.19
msgpack==1.0.4
packaging==21.3
passlib==1.7.4
protobuf==3.20.3
publicsuffix2==2.20191221
pyasn1==0.4.8
pycparser==2.21
pydivert==2.1.0
pyOpenSSL==22.1.0
pyparsing==3.0.9
pyperclip==1.8.2
pyreadline==2.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
six==1.16.0
sortedcontainers==2.4.0
tornado==6.2
typing_extensions==4.4.0
urwid==2.1.2
Werkzeug==2.2.2
wsproto==1.2.0
zipp==3.11.0
zstandard==0.19.0

**Comment by rev1si0n** [comment]
哦，知道了，你把计算机名称改成英文然后重启看看，过几天修复。
