### ISSUE TITLE
opencv支持，可以在android设备端进行aircv的图像识别

### ISSUE THREAD

**Issue by ykk648** [rev1si0n/lamda#16]
aircv电脑端跑起来没问题，如果android加入opencv库，那图像识别脚本就可以脱离电脑运行了

**Comment by rev1si0n** [comment]
有 opencv, numpy, Pillow 库但被禁用了，首先它会直接增加60-100MB左右的包体积，其次，安卓上的性能不尽人意，一次标准模板匹配耗时可能8秒左右。可以考虑单独作为一个附加包。

**Comment by ykk648** [comment]
了解 如果是这个性能开销，那确实是无法接受的
