### ISSUE TITLE
启动lamda服务后  不管是真机还是模拟器，触屏点击也无法打开应用

### ISSUE THREAD

**Issue by q1179336367** [rev1si0n/lamda#18]
启动lamda服务后  不管是真机还是模拟器，触屏点击无法打开任何应用

**Comment by q1179336367** [comment]
这是我的pip list
-rida                     12.8.0
aiowebsocket              1.0.0.dev2
altgraph                  0.17.2
anyio                     3.6.1
Appium-Python-Client      0.46
APScheduler               3.9.1
argcomplete               2.0.0
asgiref                   3.5.2
asn1crypto                1.5.1
asttokens                 2.0.5
async-generator           1.10
async-timeout             4.0.2
atomicwrites              1.4.0
attrs                     21.4.0
Automat                   20.2.0
backcall                  0.2.0
backports.zoneinfo        0.2.1
beautifulsoup4            4.7.1
better-exceptions         0.3.3
bitarray                  2.5.1
blinker                   1.4
Brotli                    1.0.9
brotlipy                  0.7.0
bs4                       0.0.1
camelot-py                0.10.1
cchardet                  2.1.7
certifi                   2021.10.8
cffi                      1.15.0
chardet                   3.0.4
charset-normalizer        2.0.12
cli-helpers               2.2.1
click                     8.1.3
cloudscraper              1.2.64
colorama                  0.4.4
common                    0.1.2
common-tool               1.5.2
configobj                 5.0.6
constantly                15.1.0
crypto                    1.4.1
cryptography              36.0.2
cssselect                 1.0.3
ctypes-snappy             1.2
cycler                    0.10.0
DBUtils                   3.0.2
ddddocr                   1.4.3
decorator                 5.1.1
delegator.py              0.1.1
Deprecated                1.2.13
deprecation               2.1.0
docker                    6.0.0
docopt                    0.6.2
easyocr                   1.6.1
et-xmlfile                1.1.0
executing                 0.8.3
feapder                   1.7.6
filelock                  3.7.1
Flask                     2.0.3
Flask-Compress            1.12
Flask-SQLAlchemy          3.0.2
flatbuffers               2.0
fonttools                 3.41.2
frida                     16.0.8
frida-dexdump             2.0.1
frida-tools               12.0.4
future                    0.18.2
geographiclib             1.52
geopy                     2.2.0
gevent                    21.12.0
gitdb                     4.0.9
GitPython                 3.1.27
greenlet                  1.1.2
grpc-interceptor          0.14.1
grpcio                    1.46.3
grpcio-tools              1.46.3
h11                       0.12.0
h2                        4.1.0
hexdump                   3.3
hpack                     4.0.0
httpcore                  0.14.7
httplib2                  0.20.4
httpx                     0.22.0
hydrogenbomb              0.2.4
hyperframe                6.0.1
hyperlink                 19.0.0
idna                      3.3
imageio                   2.21.2
importlib-metadata        4.11.4
incremental               21.3.0
influxdb                  5.3.1
intel-openmp              2019.0
ipython                   8.4.0
iso8601                   1.1.0
itchat                    1.3.10
itemadapter               0.6.0
itemloaders               1.0.4
itsdangerous              2.1.2
jedi                      0.18.1
Jinja2                    3.1.1
jmespath                  1.0.0
jnitrace                  3.3.0
JPype1                    1.4.0
jsonpath                  0.82
jsonsearch                0.0.2
kafka                     1.3.5
kafka-python              2.0.2
kaitaistruct              0.8
kiwisolver                1.1.0
lamda                     3.0.48
ldap3                     2.9.1
lief                      0.12.3
litecli                   1.9.0
logparser                 0.8.2
loguru                    0.6.0
lxml                      4.9.1
m3u8                      0.9.0
MarkupSafe                2.1.1
matplotlib-inline         0.1.3
mitmproxy                 8.0.0
mkl                       2019.0
more-itertools            8.13.0
msgpack                   1.0.4
msoffcrypto-tool          4.12.0
mss                       7.0.1
mutagen                   1.46.0
Naked                     0.1.31
names                     0.3.0
networkx                  2.8.6
ninja                     1.10.2.3
numpy                     1.23.0
objection                 1.11.0
olefile                   0.47.dev4
onnxruntime               1.11.1
opencv-python             4.5.5.64
opencv-python-headless    4.5.4.60
openpyxl                  3.0.10
outcome                   1.2.0
packaging                 21.3
pandas                    1.4.2
parsel                    1.5.1
parso                     0.8.3
passlib                   1.7.1
pdfminer.six              20220524
pdfplumber                0.7.4
pefile                    2022.5.30
pexpect                   4.8.0
pickleshare               0.7.5
pikepdf                   6.2.4
Pillow                    9.2.0
pip                       20.2.3
pipreqs                   0.4.11
pipx                      1.1.0
pluggy                    1.0.0
presto-python-client      0.8.2
prompt-toolkit            3.0.30
Protego                   0.2.1
protobuf                  3.19.4
protobuf-to-dict          0.1.0
protobuf3-to-dict         0.1.5
psutil                    5.8.0
psycopg2                  2.9.1
ptyprocess                0.7.0
publicsuffix2             2.20191221
pure-eval                 0.2.2
py                        1.11.0
pyasn1                    0.4.8
pyasn1-modules            0.2.5
pyclipper                 1.3.0.post3
pycparser                 2.19
pycryptodome              3.15.0
pycryptodomex             3.16.0
pydantic                  1.9.0
PyDispatcher              2.0.5
pydivert                  2.1.0
PyExecJS                  1.5.1
Pygments                  2.12.0
PyHamcrest                1.9.0
pyinstaller               5.1
pyinstaller-hooks-contrib 2022.7
pymongo                   4.1.1
PyMySQL                   0.9.3
pyOpenSSL                 22.0.0
pyparsing                 3.0.9
pypdf2                    2.11.2
pyperclip                 1.6.5
pypiwin32                 223
pypng                     0.20220715.0
PyQRCode                  1.2.1
pyquery                   1.4.3
pyreadline                2.1
PySocks                   1.7.1
pytesseract               0.3.9
pytest                    3.10.1
python-bidi               0.4.2
python-dateutil           2.8.2
python-dotenv             0.20.0
python-snappy             0.6.1
pytz                      2022.1
pytz-deprecation-shim     0.1.0.post0
PyVirtualDisplay          3.0
PyWavelets                1.3.0
pywin32                   304
pywin32-ctypes            0.2.0
PyYAML                    5.1
queuelib                  1.5.0
redis                     3.2.1
redis-py-cluster          2.1.3
requests                  2.27.1
requests-file             1.5.1
requests-toolbelt         0.10.1
retrying                  1.3.3
rfc3339                   6.2
rfc3986                   1.5.0
ruamel.yaml               0.17.21
ruamel.yaml.clib          0.2.6
scikit-image              0.19.3
scipy                     1.9.1
Scrapy                    2.6.1
scrapyd                   1.3.0
scrapyd-client            1.2.2
scrapydweb                1.4.0
selenium                  4.6.0
selenium-wire             5.1.0
semver                    2.13.0
service-identity          18.1.0
setuptools                60.9.3
sftp-client               1.0.4
Shapely                   1.8.4
shellescape               3.4.1
simhash                   2.1.2
six                       1.12.0
smmap                     5.0.0
smsactivate               1.4
sniffio                   1.3.0
sortedcontainers          2.4.0
soupsieve                 1.9.1
SQLAlchemy                1.4.44
sqlparse                  0.2.4
sseclient                 0.0.27
stack-data                0.2.0
tabula                    1.0.5
tabulate                  0.8.9
tifffile                  2022.8.12
tldextract                3.3.0
torch                     1.12.1
torchvision               0.13.1
tornado                   6.1
tqdm                      4.64.0
traitlets                 5.2.2.post1
trio                      0.21.0
trio-websocket            0.9.2
twisted                   22.4.0
twisted-iocpsupport       1.0.2
typing-extensions         4.2.0
tzdata                    2022.1
tzlocal                   4.2
uberegg                   0.1.1
undetected-chromedriver   3.1.6
unit-conversion           1.0.2
urllib3                   1.26.12
urllib3-secure-extra      0.1.0
urwid                     2.1.2
userpath                  1.8.0
w3lib                     1.20.0
wallbreaker               1.0.3
Wand                      0.6.8
wcwidth                   0.2.5
webdriver-manager         3.7.0
websocket-client          0.57.0
websockets                10.3
Werkzeug                  2.2.2
win-inet-pton             1.1.0
win32-setctime            1.1.0
WMI                       1.5.1
wrapt                     1.14.1
wsproto                   1.1.0
xlrd                      1.2.0
yarg                      0.1.9
youtube-dl                2021.12.17
yt-dlp                    2022.11.11
zipp                      3.8.0
zope.event                4.5.0
zope.interface            5.4.0
zstandard                 0.17.0

**Comment by q1179336367** [comment]
真机是pexel 1   安卓8  python3.8

**Comment by rev1si0n** [comment]
加你了
