### ISSUE TITLE
建议出一份详细wiki

### ISSUE THREAD

**Issue by moeik** [rev1si0n/lamda#19]
这样或许会更专业、更好
建议而已

**Comment by rev1si0n** [comment]
后面有时间会出全集使用视频，readthedoc 或者自建官网那种类型的 wiki 暂时不会有。

**Comment by fjqisba** [comment]
介绍太复杂了，看不懂

**Comment by shidalao** [comment]
非常复杂，而且这份安装文档是适配Windows 还是Ubuntu？看不懂。。。

**Comment by yingpwu** [comment]
> > 非常复杂，而且这份安装文档是适配Windows 还是Ubuntu？看不懂。。。
> 
> 那看样子录视频势在必行了，确实很多废话。

文档里面唯一的视频链接还点不开....

**Comment by laojiu** [comment]
打开视频链接里面是空的，项目看着很牛逼，建议出出视频或者文档，辛苦大佬

**Comment by tkkcc** [comment]
希望有个实战视频演示。另外lamda这个名字和ai模型重用名了，视频网站上完全搜不到。

**Comment by blueb0ne** [comment]
+1，没有教程视频么

**Comment by fangxianshenga** [comment]
需要一份教程视频

**Comment by rev1si0n** [comment]
视频教程已经开始录制并陆续发布，请查看 ISSUE https://github.com/rev1si0n/lamda/issues/80

**Comment by pkkgu** [comment]
1. 视频讲了几种证书，客户端和服务端文件、缓存目录都是不连贯的，非常的混乱。
2. windows雷电模拟器，adb命令都要加上设备名【adb -s emulator-5554 shell】【adb -s emulator-5554 forward tcp:2200 tcp:22】。
3. windows雷电模拟器，root已打开，Magisk超级用户、和模块按钮都无法点击。

**Comment by rev1si0n** [comment]
> 1. 视频讲了几种证书，客户端和服务端文件、缓存目录都是不连贯的，非常的混乱。
> 2. windows雷电模拟器，adb命令都要加上设备名【adb -s emulator-5554 shell】【adb -s emulator-5554 forward tcp:2200 tcp:22】。
> 3. windows雷电模拟器，root已打开，Magisk超级用户、和模块按钮都无法点击。

1. 假设你都是从第一篇开始完整看完的，不可能每个视频都给你完整溯源一遍所有文件产生的过程。
2. 因为你开了多个模拟器，视频也不可能给你从基础 adb 如何使用，安卓如何使用，adb 是什么讲起。
3. 那可能是 BUG，如果你还没安装 lamda 就出现这种情况，那这不是我的问题，如果是使用后，请进群提问题并把这个问题系统镜像打包发出来。

总结就是，视频没有从0讲起，如果你想看从0讲起安卓宇宙起源的视频，adb 如何安装如何使用，安卓如何使用，shell 如何使用，证书是什么，安卓怎么root，什么是 root，那么不介意你付费，我开课。

当然，里面的所有概念，我会重新录制一期去解释里面的名词都是什么意思。
