### ISSUE TITLE
一个小套路

### ISSUE THREAD

**Issue by better319** [rev1si0n/lamda#20]
手机安装vmos加上termux？套娃＋套娃？
这样就不用root了

**Comment by rev1si0n** [comment]
目前不支持在 VMOS 中运行。

**Comment by ykk648** [comment]
同样有该问题，一些金融/中国移动等app在root环境下无法使用，即使root hide也不行，如果我只需要一些UIautomator2的功能，是否一定要root？

**Comment by rev1si0n** [comment]
必须有 root 权限，因为里面太多的调用/服务和权限有关，事实上 lamda 有一个配套的百分百无法检测的 自启动 + root 方案但是暂时不会放出，今年的下半年或许会有。
