### ISSUE TITLE
装好了 但是在转圈圈

### ISSUE THREAD

**Issue by yu1chaofan** [rev1si0n/lamda#21]
![image](https://user-images.githubusercontent.com/32660987/212542653-75816c3a-6170-43fc-b190-bc73dfbd23d2.png)

**Comment by yu1chaofan** [comment]
红米note7pro 安卓9 miui10  已经root

**Comment by rev1si0n** [comment]
稍作等待，如果仍然继续，先重启手机，再启动看看（注意是否有允许安装的提示）

**Comment by yu1chaofan** [comment]
等了很久了 手机也没有提示  刷了第三方rom 可以显示了  这难道是miui的问题??
![image](https://user-images.githubusercontent.com/32660987/213626428-9009d6dc-b390-4e6c-bc66-8229e097c3e7.png)

**Comment by rev1si0n** [comment]
没有此机器无法分析这个问题，你可以选择远程调试（你需要做额外的配置），如果不介意，请留下你的微信号（查收后将会删除此条评论）

**Comment by yu1chaofan** [comment]
wx:Xcc_0826  现在手机正在弹出无障碍界面  但是不是需要打开什么

**Comment by yu1chaofan** [comment]
大佬新年好! 现在我有一台老设备红米5Plus 用magisk刷入了 lamda:3.78  继续访问65000还是在转圈圈

**Comment by yu1chaofan** [comment]
红米note7pro 安卓9 miui10 已经root
现在可以连上了 没有转圈圈的情况  但是网页显示黑屏  实际可以控制  终端界面正常
