### ISSUE TITLE
Update frida-java-bridge to support Android 13

### ISSUE THREAD

**Issue by aimardcr** [rev1si0n/lamda#22]
Where I run frida script that use `Java`, it gives the same issue as [this](https://github.com/frida/frida/issues/2218).
Can anyone help me update the version?

**Comment by rev1si0n** [comment]
> Where I run frida script that use `Java`, it gives the same issue as [this](https://github.com/frida/frida/issues/2218).
> 
> Can anyone help me update the version?

fix in next release soon

**Comment by rev1si0n** [comment]
3.77 just realeased
