### ISSUE TITLE
请教升级frida-sever的注意事项

### ISSUE THREAD

**Issue by rokith** [rev1si0n/lamda#23]
用frida-dexdump, 但本地frida版本和frida-server不一致,尝试把 {abi}.tar.gz里面的frida-server升级到最新, 再用magisk的插件方式安装, frida-server未正常启动, 查了代码,是要求frida的版本在16.0.0以下才可用么. 请教自行升级frida-server的方法

**Comment by rev1si0n** [comment]
你可以尝试降级本地的 frida 版本，无法手动升级安装包里的 frida-server ，目前不建议使用16，因为它经过了我们的测试，设备覆盖度不足。

**Comment by rev1si0n** [comment]
不建议使用 frida 16，看 frida 最近的 issue 就可以知道目前它是不稳定的，而且并未经过我们的多种机型和各个系统版本的测试。稳定后我们才会更新内置版本。

**Comment by rokith** [comment]
ok,谢了
