### ISSUE TITLE
在WSL（Windows Subsystem-Linux）中支持安卓系统

### ISSUE THREAD

**Issue by aimardcr** [rev1si0n/lamda#24]
我试着在WSL中运行lamda，lamda启动后，android突然崩溃了。
在Android WSL上用Magisk（x86_64）和lamda x86_64 v3.80进行了测试。

抱歉中文不好，我在用翻译器。

**Comment by rev1si0n** [comment]
english is ok. does frida-server works on WSA?

**Comment by rev1si0n** [comment]
before this check, please ensure that there only one frida-server running, two or more will crash the system.

**Comment by aimardcr** [comment]
Running frida-server using the latest server from the repo works fine, but running using lamda's frida-server caused segmentation fault:

![image](https://user-images.githubusercontent.com/41464808/214022218-bf3d76fb-6ed9-4298-a5ad-2e9489339398.png)

![image](https://user-images.githubusercontent.com/41464808/214022173-feeb49ed-43d1-4624-98e1-1859fc01e936.png)

Also I run command using official frida-server, the whole terminal seems to freeze but not the android. I wonder if this has something to do with this [issue](https://github.com/frida/frida/issues/1987)

**Comment by aimardcr** [comment]
> 

I see, it's okay then if there will be no support for WSA temporarily. The original repo was blocked due to use of Github Action, you cah use this [repo](https://github.com/LSPosed/MagiskOnWSALocal) to root WSA. Thank you for your amazing work!

**Comment by rev1si0n** [comment]
now WSA 2210.40000 (retail) is supported, version above is not tested but should work also.

need do some extra settings.

1 WSA Subsystem Settings -> Subsystem Resources -> choose Continuous
2 Turn off Advanced Networking (the Advanced Networking is weird)
3 Restart Subsystem
4 Connect to WSA adb 127.0.0.1:58526
5 Use `adb forward tcp:65000 tcp:65000` then access localhost:65000

if Advanced Networking is ON then step 5 will fail and you still can't reach lamda so we need turn off it.
step 1 is a suggest option.
