### ISSUE TITLE
安装过程中python执行报错

### ISSUE THREAD

**Issue by wenhairong** [rev1si0n/lamda#26]
WARNING: linker: ./python3.9: unused DT entry: type 0x6ffffffe arg 0x1e9b0
WARNING: linker: ./python3.9: unused DT entry: type 0x6fffffff arg 0x3
CANNOT LINK EXECUTABLE: cannot locate symbol "forkpty" referenced by "./python3.9"...

**Comment by rev1si0n** [comment]
提供一下机型和系统信息

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wenhairong ***@***.***>
发送时间: Friday, February 3, 2023 2:25:38 PM
收件人: rev1si0n/lamda ***@***.***>
抄送: Subscribed ***@***.***>
主题: [rev1si0n/lamda] 安装过程中python执行报错 (Issue #26)


WARNING: linker: ./python3.9: unused DT entry: type 0x6ffffffe arg 0x1e9b0
WARNING: linker: ./python3.9: unused DT entry: type 0x6fffffff arg 0x3
CANNOT LINK EXECUTABLE: cannot locate symbol "forkpty" referenced by "./python3.9"...

―

**Comment by wenhairong** [comment]
华为畅享5s， mtk机型

**Comment by rev1si0n** [comment]
这手机太老了，尽量刷最新的系统看看吧

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wenhairong ***@***.***>
发送时间: Friday, February 3, 2023 3:36:13 PM
收件人: rev1si0n/lamda ***@***.***>
抄送: REV1SI0N ***@***.***>; Comment ***@***.***>
主题: Re: [rev1si0n/lamda] 安装过程中python执行报错 (Issue #26)


华为畅享5s， mtk机型

―
