### ISSUE TITLE
其他APP无障碍服务启动  无效果

### ISSUE THREAD

**Issue by yu1chaofan** [rev1si0n/lamda#27]
经过测试发现关闭lamda后 其他APP无障碍正常
红米note7pro 安卓10 miui12 
红米5plus 安卓8.1 miui11
都是magisk刷入的lamda:3.95

**Comment by rev1si0n** [comment]
关闭过后需要重启才会生效

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yu1chaofan ***@***.***>
发送时间: Friday, February 3, 2023 2:50:34 PM
收件人: rev1si0n/lamda ***@***.***>
抄送: Subscribed ***@***.***>
主题: [rev1si0n/lamda] 其他APP无障碍服务无法启动 (Issue #27)


经过测试发现关闭lamda后 其他APP无障碍正常
红米note7pro 安卓10 miui12
红米5plus 安卓8.1 miui11
都是magisk刷入的lamda:3.95

―

**Comment by rev1si0n** [comment]
在magisk app中禁用，随后重启，或者用文档中的kill命令

**Comment by yu1chaofan** [comment]
在magisk app中禁用后  
或者 kill lamda 
其他APP无障碍服务可以正常运行了
有解决方法让lamda 和 无障碍都能使用吗

**Comment by rev1si0n** [comment]
目前不行

**Comment by yu1chaofan** [comment]
嗯嗯  好的

**Comment by wzming** [comment]
这个BUG有在V5版本修复了吗 @rev1si0n

**Comment by rev1si0n** [comment]
> 这个BUG有在V5版本修复了吗 @rev1si0n

5.1 版本已修复（仅支持安卓 8.0+)
