### ISSUE TITLE
抓包 证书问题

### ISSUE THREAD

**Issue by Kare-c** [rev1si0n/lamda#3]
大佬 抓包 这个问题Client TLS handshake failed. The client does not trust the proxy's certificate for beacons.gvt2.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')])) 一般是操作不当吗

**Comment by rev1si0n** [comment]
用浏览器打开baidu网页或者打开其他APP看看，如果能抓到，那就是你这个APP可能有sslpining之类的东西
