### ISSUE TITLE
关于 crontab 脚本不会执行

### ISSUE THREAD

**Issue by yu1chaofan** [rev1si0n/lamda#30]
环境
红米5P 安卓8.1 miui11 
红米note7pro 安卓10 miui12
都已开启不锁定屏幕
都是magisk刷入的lamda:3.98

crontab -e
![image](https://user-images.githubusercontent.com/32660987/218315944-4008f139-f09f-405d-b321-b9d379f3f55e.png)
py脚本
![image](https://user-images.githubusercontent.com/32660987/218316453-f18d1f0a-40b9-41db-9d3b-f3054df33dea.png)

重启lamda没有效果 都是看README.md操作的  不知道是哪里的问题

**Comment by rev1si0n** [comment]
crontab 无法使用 py 别名（py 是 python 的别名），crontab 不会经过 bash 所以这个别名不会存在，
把 py 改为 python 或者 python3.9。

其次，这个 reboot 的阶段，lamda 可能还没有完全加载完成，你可能需要再脚本的前几行加上 time.sleep(60) 这样。

```bash
@reboot py -u /data/usr/test.py >>/data/local/tmp/run.log 2>&1
```
你也可以像这样输出脚本的输出。

**Comment by rev1si0n** [comment]
还有这个接口，手机不能是静音模式。

**Comment by yu1chaofan** [comment]
好的  刚刚测试了一下  加上time.sleep(60)  py改成python  可以解决这个问题   感谢!
