### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 251623126** [rev1si0n/lamda#32]
**Describe the bug**
我使用magisk刷入的模块，在使用frps端口转发时,在frp面板发现好像没有转发成功，我如何查看到相关frp是否转发成功的日志

**Generate statistics**

**Comment by rev1si0n** [comment]
连不上应该是配置有问题，可以先检查一下和模板配置的差别。

## 查看 frps 的日志
vim 修改 /data/adb/modules/lamda/service.sh ，在两条 launch 命令后加上 `--logfile=/data/server.log`
```
$launch --port=${port} --logfile=/data/server.log
```
重启手机，等待一会进入 web shell，输入以下命令将过滤出 frp 相关日志。
```bash
grep '(fwd)' /data/server.log
```

完毕后移除这两个选项（否则有可能填满你的手机存储）
