### ISSUE TITLE
当我执行 pip3 install -U --force-reinstall 'lamda[frida]' 报错

### ISSUE THREAD

**Issue by sanqudui8ban** [rev1si0n/lamda#33]
当我执行 pip3 install -U --force-reinstall 'lamda[frida]' 报错
错误内容如下：
ERROR: Invalid requirement: "'lamda[frida]'"

我在 https://pypi.org/search/?q=lamda%5Bfrida%5D&o= 上搜索 lamda[frida]也没有搜索到

**Comment by rev1si0n** [comment]
去掉单引号试试

**Comment by sanqudui8ban** [comment]
是的，我刚才去掉单引号就成功了，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月22日(星期三) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rev1si0n/lamda] 当我执行 pip3 install -U --force-reinstall &#39;lamda[frida]&#39; 报错 (Issue #33)





 
去掉单引号试试
