### ISSUE TITLE
[ISSUE]安装lamda，显示ERROR: run with launch.sh instead

### ISSUE THREAD

**Issue by AugustineFulgur** [rev1si0n/lamda#39]
之后跑到bin目录下sh launch.sh也无效，使用的root权限

**Comment by yanghaoi** [comment]
咋修复的 哥

**Comment by AugustineFulgur** [comment]
> 咋修复的 哥

这么久的事了 记不太清了 应该是因为用了不支持lamda的版本吧

**Comment by AugustineFulgur** [comment]
> 咋修复的 哥

手机上的虚拟机（如光速）根据作者说法是不支持的 还有我是女的

**Comment by yanghaoi** [comment]
> > 咋修复的 哥
> 
> 手机上的虚拟机（如光速）根据作者说法是不支持的 还有我是女的

哈哈，好的小姐姐， 刚发现自己下错架构了。。（你回复好快
