### ISSUE TITLE
请教一下Android Studio Virtual Device需要怎么连接呢？

### ISSUE THREAD

**Issue by sakeri1** [rev1si0n/lamda#4]
安装成功后使用discover.py检测不到设备，Android Studio Virtual Device只能通过10.0.0.2访问电脑网络，我不知道怎么通过电脑访问Android Studio Virtual Device设备，感谢万分

**Comment by rev1si0n** [comment]
AVD 网络是独立的（类似于虚拟机，你找找有没有办法设置为桥接模式）如果没有，只能下面这样了
```bash
adb forward tcp:65000 tcp:65000
```
然后通过 127.0.0.1 访问。

**Comment by sakeri1** [comment]
我没有找到设置桥接的方式，我试试转发吧，感谢万分

**Comment by sakeri1** [comment]
您好，我在windows上运行startmitm.py时提示Read-only system partition，失败在d.install_ca_certificate(ca)这一步，请问我要怎么安装这个证书，或者我手动安装这个证书为系统证书后注释这一行可以吗？感谢

**Comment by rev1si0n** [comment]
https://github.com/rev1si0n/lamda#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%AE%89%E8%A3%85%E5%8F%8A%E5%90%AF%E5%8A%A8

参照这里的 AVD 使用步骤，要执行几条命令。

**Comment by rev1si0n** [comment]
文档里说 emulator 命令可能会找不到，这个默认应该不在 PATH 变量里，在 Android Studio 或者其 sdk 安装目录里面找，
如果是 windows，是 emulator.exe

**Comment by sakeri1** [comment]
嗯嗯，上个问题我已经解决了，是adb remount权限的问题，手动安装证书也可以使用，我首次安装成功，功能都是正常的情况下，重启设备后adb root和adb remount 都是成功的，接着我执行sh x86/bin/launch.sh时报错CRITICAL failed (invalid TZ area)，我试着重新安装了新的虚拟机也是一样的情况，请问这种应该怎么处理，感谢

**Comment by sakeri1** [comment]
可以了，非常感谢
