### ISSUE TITLE
CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "python3.9"...

### ISSUE THREAD

**Issue by YufengSoft** [rev1si0n/lamda#48]
>adb devices
List of devices attached
127.0.0.1:5555  offline
emulator-5554   device

>adb -s emulator-5554 shell getprop ro.product.cpu.abi
x86

>adb -s emulator-5554 push x86.tar.gz-install.sh /data/local/tmp
x86.tar.gz-install.sh: 1 file pushed, 0 skipped. 3.1 MB/s (151382906 bytes in 46.851s)

>adb -s emulator-5554 shell
root@aosp:/ # su
root@aosp:/ # cd  /data/local/tmp
root@aosp:/data/local/tmp # chmod 777 x86.tar.gz-install.sh
root@aosp:/data/local/tmp # sh x86.tar.gz-install.sh
Sun Jun 11 22:25:27 CST 2023 unpacking
Sun Jun 11 22:25:33 CST 2023 remove x86.tar.gz-install.sh
Sun Jun 11 22:25:33 CST 2023 starting server
CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "python3.9"...
1|root@aosp:/data/local/tmp #

**Comment by rev1si0n** [comment]
Android 版本是什么，什么模拟器

**Comment by rev1si0n** [comment]
据所知，Android studio emulator 上运行安卓低版本如 6.0 可能会出现这种问题。请尝试升级一下安卓版本。

**Comment by YufengSoft** [comment]
> Android 版本是什么，什么模拟器

安卓 5.0 的模拟器，x86

**Comment by rev1si0n** [comment]
不支持5.0
