### ISSUE TITLE
使用startmitm.py捕捉应用流量后，如何将所有流量的请求和响应保存下来？

### ISSUE THREAD

**Issue by yxnwh** [rev1si0n/lamda#5]
在mitmproxy页面，点击file-save，保存下来的只有一个flows文件，打开有很多乱码，无法导入charles或者fiddler进行进一步的分析

**Comment by rev1si0n** [comment]
mitmproxy 本身的功能已经足够完成大部分的工作。这个 flow 文件是 mitmproxy 的专有格式，可以在命令行执行命令 `mitmweb`，在打开的页面里点击 File -> Open 导入这个文件进行分析，`mitmproxy` 命令也支持打开 flow 文件，但是较为复杂。

**Comment by yxnwh** [comment]
> 

一般都用fiddler，不太了解mitmproxy，刚才google一下，才知道这个东东其实自成一系，多谢大佬解答！

**Comment by r00tit** [comment]
![image](https://user-images.githubusercontent.com/9130966/198242300-d5b47f89-b2dd-4db0-9316-f5488575d815.png)
运行这个报错python3 -m lamda.client -device 192.168.0.2

**Comment by rev1si0n** [comment]
请新开一个 ISSUE，并贴上完整异常报错，python 版本以及命令 `pip3 freeze` 的完整输出
