### ISSUE TITLE
有大佬碰到mac上的这种报错吗

### ISSUE THREAD

**Issue by william1042** [rev1si0n/lamda#50]
<img width="1333" alt="image" src="https://github.com/rev1si0n/lamda/assets/22214530/beb19b78-8639-40d3-82b6-c06258ae08d3">

**Comment by william1042** [comment]
mac上总是这种错哇   win上就正常

**Comment by rev1si0n** [comment]
检查下是不是开了代理或者有代理相关的环境变量
