### ISSUE TITLE
[ISSUE]关于配置文件properties.local

### ISSUE THREAD

**Issue by Lehcok** [rev1si0n/lamda#51]
有没有一个完整的配置文件样例？
因为我是magisk用户，为了图方便，我会先配置好文件，放入zip里，再去面具中安装，关于面具版，我遇到了一些不方便的问题：
1.无法指定端口号启动。
    如果想要指定端口号启动的话，只能手动结束服务端，去面具包里带参启动，如果可以在properties.local中配置个port=65000就很方便了。
2.配置文件位置问题。
    用面具的话，每次更改配置文件都需要把properties.local放入zip中然后重新安装吗？还是只需要按文档那样，放入指定的三个文件夹当中的其中一个就好？
希望可以给面具用户带来一些方便，尤其是在properties.local中配好port后就按着配好的端口号启动，还有就是一份完整的properties.local参考文档，麻烦大佬了

**Comment by JiaLeDe** [comment]
配置文件好像读取不到，但.pem证书可以读取，我拖入common 文件夹的properties.local内容如下：
fwd.host=xxx.xxx.xxx.xxx
fwd.port=6009
fwd.rport=12345
fwd.token=lamda
fwd.protocol=tcp
fwd.enable=true
frida.enable=false

部署完后没有连接到我的穿透服务器，访问本地65000端口时需要密码，访问远程12345时不通过，形成对比的是，我的逍遥模拟器可以。

**Comment by Lehcok** [comment]
配置文件不生效，.pem证书生效了

**Comment by Lehcok** [comment]
我的操作流程是：将properties.local和lamda.pem拖入lamda-magisk-module.zip中的common文件夹下，然后用面具安装lamda-magisk-module.zip，结果只有pem生效了，properties.local不生效

**Comment by Lehcok** [comment]
在lamda-magisk-module.zip的install.sh中，第32行：cp -af $TMPDIR/properties.local $CONFDIR下面追加了一行：cp -af $TMPDIR/properties.local /data/local/tmp解决了，如下：
....
cp -af $TMPDIR/properties.local $CONFDIR
cp -af $TMPDIR/properties.local /data/local/tmp
cp -af $TMPDIR/lamda.pem $CONFDIR

ui_print "- Please reboot your device"
popd

**Comment by Lehcok** [comment]
> 在lamda-magisk-module.zip的install.sh中，第32行：cp -af $TMPDIR/properties.local $CONFDIR下面追加了一行：cp -af $TMPDIR/properties.local /data/local/tmp解决了，如下： .... cp -af $TMPDIR/properties.local $CONFDIR cp -af $TMPDIR/properties.local /data/local/tmp cp -af $TMPDIR/lamda.pem $CONFDIR
> 
> ui_print "- Please reboot your device" popd

希望完善这个bug奥，还有以后可不可能加上自动重启的功能？就和debug一样，配置文件一改，就动态加载的哪种(和重启也差不多)

**Comment by rev1si0n** [comment]
是的，有bug，自动重载是有的，并不需要重启但是目前没有监控配置文件更改的操作后续可能会加，以及端口配置。
更改配置文件并不需要重刷模块，把配置文件放到 /data/usr 或者 /data/local/tmp 随后重启设备或者服务即可。

**Comment by rev1si0n** [comment]
下个版本将会出详细的可配置字段解释

**Comment by Lehcok** [comment]
> 下个版本将会出详细的可配置字段解释

还有一个已经关闭的bug，就是启动后访问ip:65000有手机界面和命令行，完全没有问题，但是使用pyhon去Device()的时候就出现问题了，会报错lamda.exceptions.ServiceUnavailable: unavaliable，web界面一点问题也没有，可以操作手机，python和adb都显示unavaliable，手机是小米10，miui13，安卓12

**Comment by Lehcok** [comment]
小米Mix2s，安卓10，MIUI12没有问题

**Comment by Lehcok** [comment]
红米K60，安卓12，miui13，web端没有画面，但有命令行

**Comment by rev1si0n** [comment]
> 红米K60，安卓12，miui13，web端没有画面，但有命令行

这个可能是兼容性问题，可以先尝试重启几次试试。

**Comment by rev1si0n** [comment]
> > 下个版本将会出详细的可配置字段解释
> 
> 还有一个已经关闭的bug，就是启动后访问ip:65000有手机界面和命令行，完全没有问题，但是使用pyhon去Device()的时候就出现问题了，会报错lamda.exceptions.ServiceUnavailable: unavaliable，web界面一点问题也没有，可以操作手机，python和adb都显示unavaliable，手机是小米10，miui13，安卓12


是否加入了 `frida.enable=false` 的配置，如果有的话那所有API也会被禁用。
