### ISSUE TITLE
增强安全性

### ISSUE THREAD

**Issue by Xyberonz** [rev1si0n/lamda#52]
作者你好， 我拥有一台工作机部署了Lamda， 其连接WIFI后，通过访问分配的IP:65000即可访问到Lamda控制页面。
但是这儿存在一个问题，由于这个WIFI可能会有其他人员，例如其他同事的接入，导致可能在内网端口扫描进而发现，存在未授权访问的安全隐患。

基于此，目前的方案是在不使用时断开WIFI连接。
但这其实非常的不方便，能否为Lamda web页提供前置认证的功能，或是提供简易的stop按钮，以便增强在不操作时间段的安全性。
致谢。

**Comment by Lehcok** [comment]
不是有哪个pem证书认证嘛？必须有token才能进去

**Comment by Lehcok** [comment]
tools里面有一个生成的py文件，直接运行会生成.pem，启动的时候放进去就行

**Comment by rev1si0n** [comment]
对的，指定 --certificate 命令行即可（通过 cert.py/cert.sh 生成证书)

**Comment by Xyberonz** [comment]
> 对的，指定 --certificate 命令行即可（通过 cert.py/cert.sh 生成证书)

由于是通过magisk模块安装的，通过tools在本地生成pem文件没有问题，但是指定命令行参数具体在哪里完成，似乎模块被加载整个lamda服务就已启动，没法再去热加载新的配置

**Comment by Lehcok** [comment]
> > 对的，指定 --certificate 命令行即可（通过 cert.py/cert.sh 生成证书)
> 
> 由于是通过magisk模块安装的，通过tools在本地生成pem文件没有问题，但是指定命令行参数具体在哪里完成，似乎模块被加载整个lamda服务就已启动，没法再去热加载新的配置

默认将.pem和.local两个配置文件写好后，放入commen里，从面具安装就行，如果后续想修改配置，就kill掉服务，然后去面具(应该是/data/adb/modouls/lama/bin)的模块里启动sh就行，自动加载的

**Comment by Lehcok** [comment]
> > 对的，指定 --certificate 命令行即可（通过 cert.py/cert.sh 生成证书)
> 
> 由于是通过magisk模块安装的，通过tools在本地生成pem文件没有问题，但是指定命令行参数具体在哪里完成，似乎模块被加载整个lamda服务就已启动，没法再去热加载新的配置

现在可能有个bug，需要将.local配置文件手动复制到/data/local/tmp里，然后重启服务或手机就可以了

**Comment by rev1si0n** [comment]
> > > 对的，指定 --certificate 命令行即可（通过 cert.py/cert.sh 生成证书)
> > 
> > 
> > 由于是通过magisk模块安装的，通过tools在本地生成pem文件没有问题，但是指定命令行参数具体在哪里完成，似乎模块被加载整个lamda服务就已启动，没法再去热加载新的配置
> 
> 现在可能有个bug，需要将.local配置文件手动复制到/data/local/tmp里，然后重启服务或手机就可以了

5.0 版本修复了一个 3.0 版本中存在的安全问题（使用证书仍可能导致非法访问），证书不兼容且已经不再使用 /data/local/tmp 路径。
