### ISSUE TITLE
[ISSUE]关于抓包和翻墙抓包问题

### ISSUE THREAD

**Issue by Lehcok** [rev1si0n/lamda#53]
既然自带python3.9了，为什么不把mitmproxy集成到python里面呢？

直接一个命令启动：d.mitm_proxy_start()

然后将web端口放到65000后面的路径里，如127.0.0.1:65000/mitmproxy/

翻墙的话，就将mitmproxy的socket端口参数配置为翻墙软件(如：V2rayNG)的socket端口或http端口

如：d.mitm_proxy_start(socket=18080)

此时不就是可以翻墙本地抓包了嘛？
我是看到`https://blog.palug.cn/2673.html`才有的想法，希望大佬可以加上，也省了额外配置翻墙抓包

**Comment by rev1si0n** [comment]
这个之前是有的，后来去掉了，原因是因为，需要做精简，其次mitmproxy的请求都是存在内存中的，虽然已经限制了 mitmproxy 只保留最近的1000条请求，但是扔不排除它会把你的手机内存吃掉。

**Comment by Lehcok** [comment]
> 

可不可以做精简的mitmproxy？没有可视化，不保存请求，只能通过py脚本来读取请求做处理，就像d.mitm_proxy_start(scryp='./run.py')，配置好指定的py脚本，所有请求只通过py处理？

**Comment by Lehcok** [comment]
> 这个之前是有的，后来去掉了，原因是因为，需要做精简，其次mitmproxy的请求都是存在内存中的，虽然已经限制了 mitmproxy 只保留最近的1000条请求，但是扔不排除它会把你的手机内存吃掉。

我看到的这个抓包软件他可以将请求直接用脚本接上，这个难搞嘛？
![image](https://github.com/rev1si0n/lamda/assets/63954316/04ac8f33-da93-44fc-bd5c-f791c48ec519)

**Comment by rev1si0n** [comment]
mitmproxy 也可以，但是如果说的是集成到 LAMDA 里，不难搞但是暂时不会有，因为这是一个有重叠的功能，
我们后面有可能会在 LAMDA 提供命令行模式的包，但是仍然需要自行到远程桌面执行，暂不会提供 API 接口。你也可以新建一个 ISSUE 我们将看用户投票决定是否加入。
