### ISSUE TITLE
[监视器添加无效]

### ISSUE THREAD

**Issue by dennyson-w** [rev1si0n/lamda#56]
- 添加了监视器，但是条件满足后，逻辑代码并未执行，
- 打印获取系统中所有已应用的 watcher 名称列表是空的

<img width="999" alt="image" src="https://github.com/rev1si0n/lamda/assets/7814811/fcfa6592-db4e-45b6-90d3-1567fcedaf8d">

### 以下为打印日志

<img width="723" alt="image" src="https://github.com/rev1si0n/lamda/assets/7814811/ac62667d-ba50-4d9a-8f86-e351d17fd9af">

**Comment by dennyson-w** [comment]
### 补充一下设备信息
<img width="420" alt="image" src="https://github.com/rev1si0n/lamda/assets/7814811/17d8e732-accc-409e-9c7d-7a8cd66cb301">

**Comment by rev1si0n** [comment]
感谢，这是一个BUG，请先回退客户端到 `pip install lamda==3.0.47` 版本，服务端兼容无需后退。

**Comment by dennyson-w** [comment]
@rev1si0n 多谢🙏，试了下老版本的确是OK 的，那我先用老版本，等大佬修复后再升上来吧
