### ISSUE TITLE
[AVD配置中间人后抓取不到请求]

### ISSUE THREAD

**Issue by dennyson-w** [rev1si0n/lamda#58]
###  模拟器启动lamda后，开启中间人代理，抓取不到请求，求助 @rev1si0n 

<img width="1520" alt="image" src="https://github.com/rev1si0n/lamda/assets/7814811/a4e2fb38-8fd6-424a-8ec0-e77027442e64">

<img width="1139" alt="image" src="https://github.com/rev1si0n/lamda/assets/7814811/d7b71479-5a06-4966-993f-b400e084ea03">

<img width="1913" alt="image" src="https://github.com/rev1si0n/lamda/assets/7814811/179c31cf-8471-4d5b-ae66-e175eee7ecaa">

**Comment by rev1si0n** [comment]
启动 startmitm 后请稍等一会儿（10s-1min)，关闭要抓包的APP，重新打开

**Comment by dennyson-w** [comment]
试过了，等多久都没用= =

**Comment by dennyson-w** [comment]
> 启动 startmitm 后请稍等一会儿（10s-1min)，关闭要抓包的APP，重新打开


试过了，等多久都没用= =

**Comment by rev1si0n** [comment]
你有打开过APP么，没打开哪里来的请求，请打开 Android 浏览器或者 webview。

**Comment by dennyson-w** [comment]
打开过，浏览器和APP都试过了

**Comment by rev1si0n** [comment]
你这两张图不是一起截的吧，端口都不一样。请附上宿主机系统/架构(intel/arm) 版本，Android studio (或者 Emulator) 版本，安卓系统版本/架构。

**Comment by rev1si0n** [comment]
除此之外，尝试重启模拟器再试。或者更换系统版本。

**Comment by dennyson-w** [comment]
> 你这两张图不是一起截的吧，端口都不一样。请附上宿主机系统/架构(intel/arm) 版本，Android studio (或者 Emulator) 版本，安卓系统版本/架构。

之前的图截的确实有问题，不过我后面重新试了AVD Android 7.0 和 8.0的版本，也试过Genymotion Android 11.0的版本也不行，都是arm64的的架构，我放弃了，打算继续用真机

**Comment by rev1si0n** [comment]
那你可能是在 intel/AMD 平台上使用了纯真 arm64 系统的 AVD 模拟器（qemu)，这种因为属于纯指令模拟模拟器非常卡顿，我们没有测试过。在 MAC M1 以及其他 ARM 平台的宿主机上启动的 arm64 并无问题。
