### ISSUE TITLE
遇到了一个挂代理的报错

### ISSUE THREAD

**Issue by Ggasdfg321** [rev1si0n/lamda#6]
![image](https://user-images.githubusercontent.com/65237278/194853584-15b77481-d889-400e-9cf9-56b2f763c038.png)
网络是桥接模式，不知道为什么会出现这个情况

**Comment by rev1si0n** [comment]
做以下操作来查找问题

1. ping 192.168.23.1 看是否可以 ping 通
2. 确定 192.168.23.1 这台设备上的 lamda 已经启动（可以多 launch.sh 几遍）
3. 确保 launch.sh 时没有指定 certificate
4. 启动后需要等待约30秒时间才能连接
5. 打开 http://192.168.23.1:65000 看是否显示页面

**Comment by rev1si0n** [comment]
做以下操作来查找问题

1. ping 192.168.23.148 看是否可以 ping 通
2. 确定 192.168.23.148 这台设备上的 lamda 已经启动（可以多 launch.sh 几遍）
3. 确保 launch.sh 时没有指定 certificate
4. 启动后需要等待约30秒时间才能连接
5. 打开 http://192.168.23.148:65000 看是否显示页面

**Comment by Ggasdfg321** [comment]
都检测过了，还是不行，访问http://192.168.23.148:65000/能正常打开，也没有开启代理，模拟器用的是逍遥最新版本的，安卓版本是7.1

**Comment by Ggasdfg321** [comment]
已经解决了，我用另外一台虚拟机解决了，我不知道为什么我这台开着模拟器的虚拟机执行脚本的时候会报错，我按照了上面那些操作都没有问题，访问 http://192.168.23.148:65000 也能正常访问，代理也并没有开启，还是执行会报错，换一台虚拟机试了下却又没问题

**Comment by rev1si0n** [comment]
也有可能是模拟器里后装的某些模块影响到了
