### ISSUE TITLE
增加pem证书后weditor无法使用

### ISSUE THREAD

**Issue by ykk648** [rev1si0n/lamda#61]
有没有可能在pem证书的基础上使用weditor，比较喜欢里面组件的层级显示

**Comment by rev1si0n** [comment]
目前不行，加了证书后会需要授权，需要修改 weditor 代码在请求时加上 X-Token (远程桌面密码)头才行

**Comment by ykk648** [comment]
ok，thx，希望lamda以后界面更新Hierrarchy的显示
