### ISSUE TITLE
关于5.0版本后的openvpn无法连接的问题

### ISSUE THREAD

**Issue by yu1chaofan** [rev1si0n/lamda#62]
环境:  红米note7pro,安卓10,面具

lamda5.0  5.1  都尝试过有不行

lamda3,157的openvpn是正常的,所有的配置都没有动过,升级后出现的问题.也有可能是我不会操作

![image](https://github.com/rev1si0n/lamda/assets/32660987/51fc2f51-4e4b-44aa-afa1-87e4e4b39fe8)

**Comment by rev1si0n** [comment]
尝试5.2看看

**Comment by rev1si0n** [comment]
还有这似乎不是用文档里提供的方法安装的openvpn服务器，lamda 的vpn只支持使用证书方式连接，报错日志似乎说明不支持证书方式

**Comment by rev1si0n** [comment]
以及，如果是使用 properties 文件配置，请注意不忘放在 data/local/tmp 了，不再从这个位置读取配置，给放到 /data/usr

**Comment by yu1chaofan** [comment]
![image](https://github.com/rev1si0n/lamda/assets/32660987/0b199520-ba2e-413a-bdb6-5ccfb709fcef)
上面是3.157版本使用openvpn链接正常,openvon是加载的配置文件,使用是正常的!

**Comment by yu1chaofan** [comment]
现在发现我用openvpn APP 也连不上,可能是我证书问题

**Comment by rev1si0n** [comment]
5.0 与 3.0 的 openvpn 没做过会产生类似问题的修改，使用内置接口配置看看，方便的话你也可以提供可复现的测试配置文件

**Comment by yu1chaofan** [comment]
我在3.157和5.0上面都测试过,3.157上面是确定是正常连接的,我尝试调整运行在openwrt下的openvpnserver,但是现在好像把server搞崩溃了,有办法在lamda中直接使用WireGuard client 或者 ZeroTier 吗????

**Comment by rev1si0n** [comment]
目前不行

**Comment by yu1chaofan** [comment]
大佬,这是我的配置文件https://lanzouw.com/iHGTo1blm9ch

**Comment by rev1si0n** [comment]
缺少 cipher 字段
