### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by Boy-Nine** [rev1si0n/lamda#63]
我本地安装了客户端，手机通过Magisk安装了服务端，但是我找不到/data/server/bin/launch.sh，root状态，但是手机并没有server文件目录，请问你们有遇到吗

**Comment by rev1si0n** [comment]
使用 magisk 安装后是自动启动的，不需要手动执行。

**Comment by rev1si0n** [comment]
如果你想找到他，在 /data/adb/modules 目录下查找
