### ISSUE TITLE
[ISSUE]7.0版本使用证书启动失败，提示证书错误 CRITICAL failed (invalid pem cert)

### ISSUE THREAD

**Issue by darkness-A** [rev1si0n/lamda#64]
![image](https://github.com/rev1si0n/lamda/assets/22480057/b036d8f8-5296-41b5-a1ba-fb61ffb8f392)

**Comment by darkness-A** [comment]
7.0下的tools生成的和5.x生成的都不行，不使用证书就可以正常运行，
![image](https://github.com/rev1si0n/lamda/assets/22480057/eede527c-a900-4d94-a90d-e5f9c5a9c5c5)

**Comment by rev1si0n** [comment]
请先检查证书（目前LAMDA有三个版本，3.0,5.0,7.0、3.0和其他的都不通用、5.0和7.0的证书格式是通用的、也就是说需要克隆5.0的代码生成证书才能在7.0上使用，以及你需要注意当前目录是否存在之前旧版本生成的lamda.pem，因为默认如果当前目录存在同名证书将不会生成），如果仍然出错，请附上这个出错的证书
