### ISSUE TITLE
为什么下不到7.18以前的版本了

### ISSUE THREAD

**Issue by zhishihenduo** [rev1si0n/lamda#74]
1. **问题.**   
7.18以前的版本没地方下载了。

3. **问题.**    
frida 可以带token 连接 手机 --token ***   但是  objection 新版已经无法连接了  没有--token 的案例写法 （如何让手机 停止token校验？）

5. **问题.**    
控制屏幕要是一个网页挂在哪里。要是在其他地方远程连接，永远会出现 无法操控。能把原来的网页踢掉嘛。

**Comment by rev1si0n** [comment]
7.20 之前的版本都是 beta，避免用法不统一，所以删除。

无法禁用token，因为需要做到和API联动，可使用 5.x 版本或者自行修改 objection 代码的https://github.com/sensepost/objection/blob/6c55d7e46292048d629dbe361701e5fe3e02d8d0/objection/utils/agent.py#L172 为
```python
from lamda.client import *
self.device = Device(host, port=port)
```


无法踢掉，只允许一个客户端操作屏幕，如果因为误操作导致别处连接未关闭，请重启设备或者连接API执行
```python
d.reload(True)
```

**Comment by zhishihenduo** [comment]
**问题1**   《 7.20 之前的版本都是 beta，避免用法不统一，所以删除。》
``` 
删除了。我就明白为什么找不到，用5.x 可以实现 objection 免token连接，
```

**#问题2**  《无法禁用token，因为需要做到和API联动，可使用 5.x 版本或者自行修改 objection 代码的》  
``` 
    但是不是每个人都会py 修改objection的源码，那我们不会改源码重编译objection的话。要用objection 不是以后就不能上新版了。

    能不能让 api自己去拿token 我知道这样会到时被攻击的风险，但是新版不能用objection 真的挺头疼的。要是不能用以后很多人都选择用旧版，而不会选择体验新版的功能了。

    希望 在lamda控制台层面 写个指令 d.disableFridaToken 类似这种。关闭掉。或者 服务器自动拿token 。允许前端快速访问
```

**#问题3**   《无法踢掉，只允许一个客户端操作屏幕，如果因为误操作导致别处连接未关闭，请重启设备或者连接API执行》
``` 
#完美解决
d.reload(True)
```
