### ISSUE TITLE
Implement frida anti-detection

### ISSUE THREAD

**Issue by Dev4Mod** [rev1si0n/lamda#75]
There are some patches to remove frida detection that can be useful to avoid detection of some apps protected by encryption, such as Love encryption Enterprise, would it be possible to apply these patches?
[strongR](https://github.com/hluwa/Patchs/tree/master/strongR-frida/frida-core)

**Comment by rev1si0n** [comment]
lamda's frida already built with these patches and our custom patch.

**Comment by Dev4Mod** [comment]
I think it's because I'm using an older version but I'll test it, thanks for responding!
