### ISSUE TITLE
对安装了多开的app,例如炼妖壶多开,如何运行userid非0用户的app?

### ISSUE THREAD

**Issue by smallwaye** [rev1si0n/lamda#76]
例如用adb实现的命令
am start --user 14 -n  com.sampleapp/.MainActivity
如何用d.application切换用户执行,或者执行的时候加上用户id这个参数?
谢谢

**Comment by rev1si0n** [comment]
双开应用已经支持，跟随下个版本一周内发布

```python
d.application("com.tencent.mm", user=999)
```
