### ISSUE TITLE
关于证书安装的问题

### ISSUE THREAD

**Issue by onelucksnake** [rev1si0n/lamda#78]
关于证书安装的部分"[https://github.com/rev1si0n/lamda/wiki/安装证书](https://github.com/rev1si0n/lamda/wiki/%E5%AE%89%E8%A3%85%E8%AF%81%E4%B9%A6)"部分，我尝试在 ANDROID 13 上执行该证书注入代码，但我失败了；

当然，其实我是知道，GOOGLE针对证书安全的问题，在 ANDROID 13/14 使用了新的技术，所以我测试了你的证书注入方法，显然也突破不了证书的安全防护，所以我想问一下，说明文档中的证书注入方法，在什么情况下适用？

又或者说，只是我的方法错误了，实际上你的证书注入方法，适用于 ANDROID 13/14 ？

补充：目标是注入丟安卓系统的"系统证书组"中~

**Comment by rev1si0n** [comment]
是的，针对安卓14做了特定的操作，但在我们目前有的安卓13中并未发现系统使用了新的证书读取逻辑 (apex) 所以并没有在安卓13上应用此逻辑（我们没有实体设备，所以目前只在AVD上测试，并且都工作的很好）

**Comment by onelucksnake** [comment]
> 是的，针对安卓14做了特定的操作，但在我们目前有的安卓13中并未发现系统使用了新的证书读取逻辑 (apex) 所以并没有在安卓13上应用此逻辑（我们没有实体设备，所以目前只在AVD上测试，并且都工作的很好）

我是在实体机上测试的，使用的是PIXEL 4，使用的系统是版本是"AOSP ON SUNFISH"（Android 13），根据我自己的检查，该系统上已经在使用APEX，我应该如何在ANDROID 13上使用ANDROID 14的方法去测试证书注入？

**Comment by rev1si0n** [comment]
抱歉，目前暂时不兼容并且安卓14的实现方法比较简陋，后续会修改为更优雅的实现方法。

**Comment by rev1si0n** [comment]
下一个版本将会兼容安卓13新证书，预计周内发布
