### ISSUE TITLE
Frida 检测反馈

### ISSUE THREAD

**Issue by Nuyoah-Yc** [rev1si0n/lamda#82]

**Comment by rev1si0n** [comment]
内置的 frida 无法替换

**Comment by Nuyoah-Yc** [comment]
> 内置的 frida 无法替换

不能替换的话，frida有特征会被检测，其次这个版本连接不上

**Comment by rev1si0n** [comment]
连接不上是因为需要用特定的连接方式，文档里有写，被检测到，除非是你自己做了patch，内置的版本不是原版的，已经具备了开源的反检测补丁，同时我们也做了改动，如果有哪个第三方的没检测到 lamda 的被检测到了请直接提issue，在没用的情况下请不要随意否定

**Comment by Nuyoah-Yc** [comment]
> 连接不上是因为需要用特定的连接方式，文档里有写，被检测到，除非是你自己做了patch，内置的版本不是原版的，已经具备了开源的反检测补丁，同时我们也做了改动，如果有哪个第三方的没检测到 lamda 的被检测到了请直接提issue，在没用的情况下请不要随意否定

这个项目非常的好，是因为我没仔细看文档的缘故。加油

**Comment by Nuyoah-Yc** [comment]
> 连接不上是因为需要用特定的连接方式，文档里有写，被检测到，除非是你自己做了patch，内置的版本不是原版的，已经具备了开源的反检测补丁，同时我们也做了改动，如果有哪个第三方的没检测到 lamda 的被检测到了请直接提issue，在没用的情况下请不要随意否定

您好，过不了Hunter检测

**Comment by rev1si0n** [comment]
附上下载地址

**Comment by rev1si0n** [comment]
附上apk下载地址在 2024年4月19日，15:21，尤创 ***@***.***> 写道：﻿

连接不上是因为需要用特定的连接方式，文档里有写，被检测到，除非是你自己做了patch，内置的版本不是原版的，已经具备了开源的反检测补丁，同时我们也做了改动，如果有哪个第三方的没检测到 lamda 的被检测到了请直接提issue，在没用的情况下请不要随意否定

您好，过不了Hunter检测

**Comment by rev1si0n** [comment]
已经知道此软件检测到调试的缘由了，后面可能会出解决方案，解决方案可能会影响 frida 的一部分功能。顺便说一下，他检测到这个的原因所使用的方法，一般正常app不会去使用也没有太大必要去使用。最简单的手动过的方法，降级安卓系统到 9.0 或者更低。

**Comment by rev1si0n** [comment]
反检测新版已经发布，关注公众号或者 bilibili 查看使用方法

**Comment by Nuyoah-Yc** [comment]
沙特阿拉伯的NAFATH好像也过不了

**Comment by rev1si0n** [comment]
> 沙特阿拉伯的NAFATH好像也过不了

如果你的设备过不了我们接受收费定制，请联系邮箱 ihaven0emmail@gmail.com

![demo](https://github.com/rev1si0n/lamda/assets/13597216/97bc3211-dd0a-4ff7-b179-4b8cec379826)
